### model
model_name_or_path: $SCRATCH/ocr_cleaning/models
new_special_tokens: <|start_header_id|>,<end_header_id|>,<|eot_id|> #token added with the chat template

### method
stage: sft # supervised fine tuning
do_train: true
finetuning_type: full
use_badam: true # use BADAM not classical full-finetuning, faster!
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 2
flash_attn: fa2
deepspeed: $SCRATCH/ocr_cleaning/config/ds_z3_config.json #deepspeed

### dataset
dataset: training_dataset # comma separated datasets, defined in: data/dataset_info.json
template: llama3 # chat template
cutoff_len: 2048
max_samples: 560000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: $SCRATCH/ocr_cleaning/out # output directory
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.03e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps 
eval_steps: 100

### logging
report_to: wandb
run_name: training_cineca # the name of the run